model: gpt-4o-mini
temperature: 0.2

# UI tone and encouragement settings
ui:
  tone: neutral  # Can be: neutral, encouraging, professional
  encouragement:
    enabled: false
    phrases: 
      - "Great choice!"
      - "Excellent!"
      - "Perfect!"
      - "Well done!"
  confirmations:
    style: neutral  # neutral, enthusiastic, minimal
    neutral_phrases:
      - "Updated."
      - "Done."
      - "Applied."
      - "Changed."
      - "Modified."

# Text processing limits and settings
text:
  limits:
    body_max_chars: 1024
    header_max_chars: 60
    footer_max_chars: 60
    template_name_max_chars: 64
  shorten:
    enabled: true
    target_length: 140
    aggressive_mode: false

# NLP configuration for intent parsing and synonyms
nlp:
  synonyms:
    add: ["add","include","insert","attach","create","put","append","make","give","provide"]
    button: ["button","buttons","cta","quick reply","quick replies","reply option","action","actions"]
    url: ["url","link","website","web","open","visit"]
    phone: ["phone","call","contact","dial","ring"]
    brand: ["brand","company","org","organization","business","sender","brand name","company name"]
    header: ["header","title","heading"]
    footer: ["footer","sign-off","signature"]
    shorten: ["shorten","shorter","make it short","condense","trim","crisper","concise","brief","reduce"]
    name: ["name","title","template name"]
    body: ["body","message","text","content","copy"]
    remove: ["remove","delete","drop","clear","eliminate","take out"]
    replace: ["replace","change","swap","substitute","update"]
    modify: ["modify","edit","adjust","tweak","alter"]
  languages: ["en","hi","es"]
  parsing:
    case_sensitive: false
    extract_quotes: true     # extract quoted text as raw labels
    word_to_number: true     # convert "three" to "3"
    max_extracted_items: 20  # safety limit for bulk operations
  directive_processing:
    enabled: true
    strict_mode: true        # enforce exact counts and limits
    allow_overrides: false   # prevent exceeding hard limits
    preserve_order: true     # maintain user-specified order

history:
  max_turns: 200
  log_llm_io: true  # your code logs regardless; this is just a hint

# Validation and compliance settings
validation:
  phone_numbers:
    normalize: true           # normalize phone format
    require_country_code: true
    allowed_formats: ["+1XXXXXXXXXX", "+91XXXXXXXXXX"]
  urls:
    validate_https: true      # prefer HTTPS URLs
    check_reachability: false # ping test (expensive)
    max_length: 512
  meta_compliance:
    enforce_guidelines: true  # follow Meta's template guidelines
    check_prohibited_content: true
    validate_button_limits: true
  template_quality:
    min_score: 0.7           # quality threshold (0-1)
    check_readability: true
    check_engagement: true

limits:
  buttons:
    max_total: 10      # overall hard cap across all types
    max_visible: 3     # visible on-card; rest under "See all"
    max_url: 2         # URL button limit
    max_phone: 1       # phone number button limit
    max_quick_reply: 10  # quick reply button limit
    deduplication: true  # remove duplicate button labels
    enforce_counts: true # strictly enforce count directives
  text:
    body_max_chars: 1024
    header_max_chars: 60
    footer_max_chars: 60
    min_body_chars: 10   # minimum body text length
  template:
    name_max_chars: 64
    name_pattern: "^[a-z0-9_]{1,64}$"
  processing:
    max_iterations: 5    # max rounds of directive processing
    timeout_seconds: 30  # max processing time per request

creation_payload_schema:
  $schema: "http://json-schema.org/draft-07/schema#"
  type: object
  required: [name, language, category, components]
  properties:
    name: { type: string, pattern: "^[a-z0-9_]{1,64}$" }
    language: { type: string }  # e.g., en_US, hi_IN
    category: { type: string, enum: [MARKETING, UTILITY, AUTHENTICATION] }
    components:
      type: array
      minItems: 1
      items:
        type: object
        required: [type]
        properties:
          type: { type: string, enum: [HEADER, BODY, FOOTER, BUTTONS] }
          format: { type: string, enum: [TEXT, IMAGE, VIDEO, DOCUMENT, LOCATION] }
          text: { type: string }
          example: { type: [object, array, string, 'null'] }
          buttons:
            type: array
            items:
              type: object
              required: [type, text]
              properties:
                type: { type: string, enum: [QUICK_REPLY, URL, PHONE_NUMBER] }
                text: { type: string }
                url: { type: string }
                phone_number: { type: string }
                payload: { type: string }
  additionalProperties: false
  allOf:
    # Header format conditionals: TEXT requires text, media forbids text
    - if:
        properties:
          components:
            contains:
              allOf:
                - properties: { type: { const: HEADER } }
                - properties: { format: { const: TEXT } }
      then:
        properties:
          components:
            contains:
              allOf:
                - properties: { type: { const: HEADER } }
                - properties: { format: { const: TEXT } }
                - required: [text]
    # Non-TEXT headers must not have text field
    - if:
        properties:
          components:
            contains:
              allOf:
                - properties: { type: { const: HEADER } }
                - properties: { format: { enum: [IMAGE, VIDEO, DOCUMENT, LOCATION] } }
      then:
        properties:
          components:
            contains:
              allOf:
                - properties: { type: { const: HEADER } }
                - properties: { format: { enum: [IMAGE, VIDEO, DOCUMENT, LOCATION] } }
                - not: { required: [text] }
    # AUTHENTICATION category restrictions
    - if:
        properties: { category: { const: AUTHENTICATION } }
      then:
        properties:
          components:
            allOf:
              # No FOOTER allowed
              - not:
                  contains: { properties: { type: { const: FOOTER } } }
              # No BUTTONS allowed  
              - not:
                  contains: { properties: { type: { const: BUTTONS } } }
              # Only TEXT headers allowed (if header present)
              - not:
                  contains:
                    allOf:
                      - properties: { type: { const: HEADER } }
                      - properties: { format: { enum: [IMAGE, VIDEO, DOCUMENT, LOCATION] } }

lint_rules:
  # Meta compliance validation
  meta_guidelines:
    enforce_character_limits: true
    check_placeholder_rules: true
    validate_category_restrictions: true

  # Placeholder hygiene
  placeholders:
    enforce_sequential: true      # {{1}}, {{2}}, ...
    forbid_adjacent: true         # no "{{1}}{{2}}"
    forbid_edge_positions: true   # not at very start or end of BODY

  # Button constraints (inherits from limits.buttons)
  buttons:
    use_global_limits: true      # inherit from limits.buttons section
    validate_duplicates: true
    enforce_type_limits: true

  # Language and naming constraints
  languages:
    whitelist: [en_US, hi_IN, es_MX, fr_FR, de_DE]
  naming:
    reserved_prefixes: [test_, tmp_, demo_]

  # Category-specific constraints
  category_constraints:
    AUTHENTICATION:
      allow_buttons: false
      allow_footer: false  # AUTH templates should not have footers
      allow_media_header: false
      allowed_header_formats: [TEXT]  # Only TEXT headers allowed for AUTH
    MARKETING:
      allow_buttons: true
      allow_footer: true
      allowed_header_formats: [TEXT, IMAGE, VIDEO, DOCUMENT, LOCATION]
    UTILITY:
      allow_buttons: true
      allow_footer: true
      allowed_header_formats: [TEXT, IMAGE, VIDEO, DOCUMENT, LOCATION]

  # Header format validation
  header_formats:
    TEXT:
      max_length: 60
      max_variables: 1
      require_text: true
    IMAGE:
      require_example: true
      forbid_text: true
    VIDEO:
      require_example: true
      forbid_text: true
    DOCUMENT:
      require_example: true
      forbid_text: true
    LOCATION:
      require_example: false  # Optional for LOCATION
      forbid_text: true

  # Components configuration for enhanced directive processing
  components:
    buttons:
      defaults_by_category:
        MARKETING: ["Shop now", "Learn more", "Contact us"]
        UTILITY: ["View details", "Update info", "Get help"]
        AUTHENTICATION: []  # buttons not allowed anyway
      smart_suggestions: true    # suggest contextual buttons
      auto_deduplication: true   # remove duplicates automatically
      preserve_user_order: true  # maintain user-specified order
    text:
      shorten:
        enabled: true
        target_length: 140
        preserve_key_info: true   # keep important details
        use_ai_summary: true      # use LLM for intelligent shortening
    processing:
      directive_modes:
        strict: true              # enforce exact counts
        permissive: false         # allow approximations
        interactive: true         # ask for clarification when ambiguous
    header:
      formats:
        TEXT:
          max_length: 60
          max_variables: 1
          require_text: true
          variable_example_required: true
        IMAGE:
          require_example: true
          forbid_text: true
          allowed_mime_types: ["image/jpeg", "image/png"]
        VIDEO:
          require_example: true
          forbid_text: true
          allowed_mime_types: ["video/mp4", "video/3gpp"]
        DOCUMENT:
          require_example: true
          forbid_text: true
          allowed_mime_types: ["application/pdf", "text/plain"]
        LOCATION:
          require_example: false
          forbid_text: true
          master_switch: true  # LOCATION is master format
      category_restrictions:
        AUTHENTICATION:
          allowed_formats: ["TEXT"]
        MARKETING:
          allowed_formats: ["TEXT", "IMAGE", "VIDEO", "DOCUMENT", "LOCATION"]
        UTILITY:
          allowed_formats: ["TEXT", "IMAGE", "VIDEO", "DOCUMENT", "LOCATION"]

  # Disallowed links (safety/compliance)
  forbidden_links:
    - "^https?://wa\\.me/"
    - "^javascript:"
    - "^https?://bit\\.ly/"
    - "^data:"

naming_policy:
  auto_snake_case: true
  max_len: 64
  reserved_prefixes: []
